services:
  # 博客应用服务
  - type: web
    name: myblog
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py wsgi:app
    envVars:
      - key: FLASK_CONFIG
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: myblog-db
          property: connectionString

databases:
  # 数据库服务
  - name: myblog-db
    databaseName: myblog
    user: myblog_user
